name: Release (npm)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Verify tag matches package.json version
        run: |
          TAG="${GITHUB_REF_NAME}"
          PKG_VERSION="v$(node -p "require('./package.json').version")"
          echo "Tag: $TAG | package.json: $PKG_VERSION"
          if [ "$TAG" != "$PKG_VERSION" ]; then
            echo "Tag and package.json version mismatch" >&2
            exit 1
          fi

      - name: Run tests (quick)
        run: |
          npm run test:errors:all

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --provenance --access public

